gems:
  - jekyll-paginate

title: Candida
description:
    <a href="https://jdh8.org">Integration by me</a> 的
    <a href="https://jekyllrb.com/" rel="external">Jekyll</a> 測試版

paginate: 10
baseurl: /candida
permalink: /:year/:month/:title/
