gems:
  - jekyll-paginate

title: Integration by me
description: 你們必曉得真理，真理必叫你們得以自由。
paginate: 10
baseurl: /jdh8.org
permalink: /:title/
timezone: Asia/Taipei

defaults:
  - scope:
        path: ""
    values:
        author: jdh8
